### PR TITLE
给它发信按钮w

### PR DESCRIPTION
**Pull request by zhzhzoo**

### CODE REVIEW

**Comment by huxuan** [comment]
@JeldorPKU Can you help me to confirm whether this is work?

**Comment by JeldorPKU** [comment]
能改成`给TA发信`吗……这里用“它”感觉怪怪的……

**Comment by JeldorPKU** [comment]
亲测能用，上面说的那条改改吧～ @zhzhzoo

**Comment by JeldorPKU** [comment]
发现两个问题：
- 可以给自己发信……
- 其实帖子那里就有“发消息”这个按钮，为啥要这个？

**Comment by huxuan** [comment]
@JeldorPKU Sorry for the ignorance of existing message sent feature. As we've already have, I don't think we need this implementation actually.

**Comment by huxuan** [comment]
@zhzhzoo Can you explain more about why we need this implementation?

**Comment by zhzhzoo** [comment]
嗯实在抱歉一直没有看见“发信息”。。。那么这个 PR 就没啥用了

**Comment by huxuan** [comment]
Close as discussed.

**Pull request closed without merging**
