### PR TITLE
add configs and tests for cgi scripts

### PR DESCRIPTION
**Pull request by QwertyJack**

### CODE REVIEW

**Comment by huxuan** [comment]
Can you give more information about what is this for?

**Comment by zhzhzoo** [comment]
哈哈好复杂还得给 root 才能执行

**Comment by QwertyJack** [comment]
Apache的cgi配置

**Comment by huxuan** [comment]
Then why should add it to this repository? for solving old link issue?

**Comment by QwertyJack** [comment]
@zhzhzoo why?

**Comment by zhzhzoo** [comment]
嗯就是大家觉得代码要版本控制起来最好

**Comment by zhzhzoo** [comment]
然后 apache 配置脚本什么的要不要版本控制，如果要的话放什么 repo，就是系统管理员自己怎么喜欢怎么来吧。。。

**Comment by huxuan** [comment]
@zhzhzoo Please answer the question directly. What's is this code for? If it's only apache configuration. I would prefer to move it to CAPU-ENG/CAPU-SA repo.

**Comment by huxuan** [comment]
I will revert it temporarily cause it is accidentally merged by my casual click. Please send a new pull request with more specific information about the usage.

**Comment by zhzhzoo** [comment]
嗯是“老主页安装帮助”这种东西

**Comment by huxuan** [comment]
Then I think it should belong to CAPU-SA repo. If you have any different opinions, please feel free to tell me.

**Pull request merged**
