### PR TITLE
按 ctrl-enter 直接发帖 Fix #11

### LINKED ISSUE #11: TODO list - 直接回复帖子
用ctrl+enter直接回复，不去按回复按钮

### PR DESCRIPTION
**Pull request by zhzhzoo**

### CODE REVIEW

**Comment by huxuan** [comment]
Hi @zhzhzoo, Thanks for you contribution!

I got following errror when use it for the first time and by press ctrl+Enter for the second time, it seems to work. Can you help me to confirm whether it works on your side?

And another question is that #11 is used for REPLY a thread not for new a thread. So I would suggest you remove the Fix #11 in your PR title.

snip20150119_14

**Comment by JeldorPKU** [comment]
Nothing happens when I press Control-Return. It only starts a new line. I tested your work on Safari.

**Comment by huxuan** [comment]
OK, then maybe the problem is about the title. This PR doesn't fix #11 completely. Please remove that trigger. But you can still make a reference to #11.

**Comment by zhzhzoo** [comment]
啊 我错了。。。没有改掉回复界面应该把回复界面改掉~

**Comment by JeldorPKU** [comment]
我们真的还要继续弄这个吗？还是直接去弄新的？

**Comment by huxuan** [comment]
@JeldorPKU 代码修改没有啥冲突，应该没啥大问题。

**Comment by huxuan** [comment]
@zhzhzoo 修改代码之前先`rebase`一下`upstream/master`吧，如果不确定`git`怎么用可以等当面一起搞一下。

**Comment by zhzhzoo** [comment]
@huxuan 好吧呀。。。也许是过了太长时间的缘故吧～～

**Comment by huxuan** [comment]
经常rebase是好习惯，一方面是为了提交pull request的时候减小冲突的可能性，另一方面本身代码如果和别的代码耦合比较大的话，在最新的代码里测试也是相对而言更靠谱的。

**Comment by huxuan** [comment]
Close as no further response for a long time. Feel free to reopen it when ready.

**Pull request closed without merging**
