### PR TITLE
允许二十六进制tid

### PR DESCRIPTION
**Pull request by zhzhzoo**
以及求个服务器权限需要写些 rewrite 什么的

### CODE REVIEW

**Comment by huxuan** [comment]
改成二十六进制的好处是？

**Comment by zhzhzoo** [comment]
方便老版论坛访问呀~
老版论坛和新版的唯一区别就是 tid 的进制数了，比如下面那个 ames 是 26 进制数。
http://www.chexie.net/cgi-bin/bbs.pl?see=ames&b=4&p=1
这个 url 等价于
http://www.chexie.net/bbs/content/?tid=8235&bid=4&p=1
这样搞个 rewrite 就可以支持老版论坛 url 了

**Comment by zhzhzoo** [comment]
以及代码写错了我少加了1.。。。

**Comment by huxuan** [comment]
OK, if this is true. I agree with the purpose of this PR. But currently we don't have enough time to review&test this one. Let's consider to focus on capurace instead currently. I will lock this pull request and feel free to kick me after the deadline of capurace.

**Comment by JeldorPKU** [comment]
如果改了的话，原来的tid会不会和现在的tid有冲突啊……我想应该没有不过还是有点担心，不知道当时 @ckcz123 是直接转移过来的还是重新插入的……

**Comment by huxuan** [comment]
Close as no further response for a long time. Feel free to reopen it when ready.

**Pull request closed without merging**
