### PR TITLE
改掉客户端编辑显示来源网页bug. Fix #91.

### LINKED ISSUE #91: 编辑帖子后 帖子来源会错误
比如用客户端发帖 再编辑后 显示的发帖来源就是网页版了。。。

### PR DESCRIPTION
**Pull request by zhzhzoo**

### CODE REVIEW

**Comment by zhzhzoo** [comment]
口亨居然都一去妙峰就不给 merge 代码了。。。

**Comment by huxuan** [comment]
Sorry, I have make enough time to test it. I will do it soon tomorrow……

**Comment by goodman-capu** [comment]
这个地方的确是这样的

**Comment by huxuan** [comment]
@goodman-capu  Thanks for your confirmation.
@zhzhzoo  Thanks for you hard work!

**Pull request merged**
